wget https://uproai.blob.core.windows.net/models/原神/枫原万叶/枫原万叶-e10.ckpt
wget https://uproai.blob.core.windows.net/models/原神/纳西妲/纳西妲-e10.ckpt
wget https://uproai.blob.core.windows.net/models/原神/胡桃/胡桃-e10.ckpt
wget https://uproai.blob.core.windows.net/models/原神/芙宁娜/芙宁娜-e10.ckpt
wget https://uproai.blob.core.windows.net/models/原神/那维莱特/那维莱特-e10.ckpt
wget https://uproai.blob.core.windows.net/models/原神/钟离/钟离-e10.ckpt
wget https://uproai.blob.core.windows.net/models/原神/雷电将军/雷电将军-e10.ckpt
wget https://uproai.blob.core.windows.net/models/原神/魈/魈-e10.ckpt
wget https://uproai.blob.core.windows.net/models/佳代子/佳代子-e10.ckpt
wget https://uproai.blob.core.windows.net/models/奥空绫音/奥空绫音-e10.ckpt
wget https://uproai.blob.core.windows.net/models/安守实里/安守实里-e10.ckpt
wget https://uproai.blob.core.windows.net/models/戒野美咲/戒野美咲-e10.ckpt
wget https://uproai.blob.core.windows.net/models/才羽绿/才羽绿-e10.ckpt
wget https://uproai.blob.core.windows.net/models/春原瞬/春原瞬-e10.ckpt
wget https://uproai.blob.core.windows.net/models/歌原/歌原-e10.ckpt
wget https://uproai.blob.core.windows.net/models/爱丽丝/爱丽丝-e10.ckpt
wget https://uproai.blob.core.windows.net/models/爱清枫香/爱清枫香-e10.ckpt
wget https://uproai.blob.core.windows.net/models/狐坂若藻/狐坂若藻-e10.ckpt
wget https://uproai.blob.core.windows.net/models/白洲梓/白洲梓-e10.ckpt
wget https://uproai.blob.core.windows.net/models/白石歌原/白石歌原-e10.ckpt
wget https://uproai.blob.core.windows.net/models/苍森美弥/苍森美弥-e10.ckpt
wget https://uproai.blob.core.windows.net/models/阿慈谷日富美/阿慈谷日富美-e10.ckpt
wget https://uproai.blob.core.windows.net/models/阿露/阿露-e10.ckpt
wget https://uproai.blob.core.windows.net/models/鬼方佳代子/鬼方佳代子-e10.ckpt