wget https://uproai.blob.core.windows.net/models/原神/枫原万叶/枫原万叶_e10_s290.pth
wget https://uproai.blob.core.windows.net/models/原神/纳西妲/纳西妲_e10_s400.pth
wget https://uproai.blob.core.windows.net/models/原神/胡桃/胡桃_e10_s210.pth
wget https://uproai.blob.core.windows.net/models/原神/芙宁娜/芙宁娜_e10_s290.pth
wget https://uproai.blob.core.windows.net/models/原神/那维莱特/那维莱特_e10_s280.pth
wget https://uproai.blob.core.windows.net/models/原神/钟离/钟离_e10_s1120.pth
wget https://uproai.blob.core.windows.net/models/原神/雷电将军/雷电将军_e10_s210.pth
wget https://uproai.blob.core.windows.net/models/原神/魈/魈_e10_s600.pth
wget https://uproai.blob.core.windows.net/models/佳代子/佳代子_e10_s140.pth
wget https://uproai.blob.core.windows.net/models/奥空绫音/奥空绫音_e10_s250.pth
wget https://uproai.blob.core.windows.net/models/安守实里/安守实里_e10_s190.pth
wget https://uproai.blob.core.windows.net/models/戒野美咲/戒野美咲_e10_s180.pth
wget https://uproai.blob.core.windows.net/models/才羽绿/才羽绿_e10_s170.pth
wget https://uproai.blob.core.windows.net/models/春原瞬/春原瞬_e10_s170.pth
wget https://uproai.blob.core.windows.net/models/歌原/歌原_e10_s150.pth
wget https://uproai.blob.core.windows.net/models/爱丽丝/爱丽丝_e10_s270.pth
wget https://uproai.blob.core.windows.net/models/爱清枫香/爱清枫香_e10_s250.pth
wget https://uproai.blob.core.windows.net/models/狐坂若藻/狐坂若藻_e10_s150.pth
wget https://uproai.blob.core.windows.net/models/白洲梓/白洲梓_e10_s180.pth
wget https://uproai.blob.core.windows.net/models/白石歌原/白石歌原_e10_s280.pth
wget https://uproai.blob.core.windows.net/models/苍森美弥/苍森美弥_e10_s190.pth
wget https://uproai.blob.core.windows.net/models/阿慈谷日富美/阿慈谷日富美_e10_s150.pth
wget https://uproai.blob.core.windows.net/models/阿露/阿露_e10_s280.pth
wget https://uproai.blob.core.windows.net/models/鬼方佳代子/鬼方佳代子_e10_s160.pth
wget https://uproai.blob.core.windows.net/models/近卫南/近卫南_e10_s170.pth
wget https://uproai.blob.core.windows.net/models/静山真白/静山真白_e10_s130.pth